print("=" * 50)
print("LINARIO - Pure Python Linear Algebra")
print("=" * 50)
print()
print("Welcome to Linario!")
print()
print("This is a learning project built from scratch to explore")
print("matrices and vectors using only pure Python - no libraries.")
print()
print("The goal? Master Python basics while diving into the")
print("fundamentals of linear algebra through hands-on coding.")
print()
print("Everything here is built from the ground up to understand")
print("how matrix and vector operations actually work.")
print()
print("Status: Early Development - Just Getting Started!")
print("=" * 50)
print()